### PR TITLE
Added flatlaf for a nicer UI

### PR DESCRIPTION
**Pull request by craig-mcd**
Maven updated to include flatlaf 1.1.2
Swing updated to use flatlaf

### CODE REVIEW

**Comment by alblue** [comment]
Thanks for the patch, but I am trying to keep this dependency free, and in any case I prefer the default look and feel. However, it's not meant to be a real GUI app as much as a demonstration of how byte-codes work ;-)

**Comment by CraigMcDonaldCodes** [comment]
Sure, it does look pretty bad on linux! Do you have any plans to add more features or will it stay as a demo app?

**Comment by alblue** [comment]
I created it as a companion demo app for a presentation I was giving for the London Java Community:

https://speakerdeck.com/alblue/bite-sized-bytecode-and-classloaders

There's a video that was recorded as well:

https://www.youtube.com/watch?v=_ZF1HDTjSSY

If I run this again there are a few issues (mostly in the issue tracker) of things that aren't implemented, including things like new, arrays etc.

It's possible that I won't get round to updating it further though; I forget where I was with exception handling and recovery but I suspect that's missing.

**Comment by CraigMcDonaldCodes** [comment]
I was at the LJC talk, it was very good. I'll just fiddle around with my fork. Thanks for taking the time to respond.

Don't forget about writing that book about JVM internals you mentioned on LJC slack.

**Comment by alblue** [comment]
Yeah, it’s on my ever increasing list of things to do …

**Pull request closed without merging**
